# DISCRIMINATOR
disc_hidden_units: [16, 32]
dropout_rate: 0.3

# GENERATOR
gen_hidden_units: [128, 256, 512]
latent_dims: 15
output_dims: 1

# DATA
image_dims: [28, 28, 1]
batch_size: 32

# TRAINING
model_dir: "../saved_models/dc_gan"
epochs: 100
lr: 0.0001
display_images: 10